select * from startups;
select count(*) from startups;
select sum(valuation) FROM STARTUPS;
SELECT MAX(RAISED) FROM STARTUPS WHERE STAGE ="SEED";
SELECT NAME,MIN(FOUNDED) FROM STARTUPS;
SELECT AVG(VALUATION) FROM STARTUPS;
SELECT AVG(VALUATION) , CATEGORY FROM STARTUPS
GROUP BY CATEGORY;
SELECT ROUND(AVG(VALUATION),2) , CATEGORY FROM STARTUPS
GROUP BY CATEGORY
ORDER BY 1 DESC;
SELECT CATEGORY, COUNT(*) FROM STARTUPS
GROUP BY 1
HAVING COUNT(*)>3;
SELECT location, AVG(employees)
FROM startups
GROUP BY location
HAVING AVG(EMPLOYEES) > 500;
